# Generated by Django 6.1 on 2026-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_covers/'),
        ),
    ]
