# Generated by Django 6.1 on 2026-08-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_schooclass_student_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='schooclass',
            new_name='schoolclass',
        ),
    ]
