# Generated by Django 6.1 on 2026-09-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_schooclass_student_schoolclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schoolclass',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
