# Generated by Django 6.1 on 2026-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver/'),
        ),
    ]
