# Generated by Django 6.1 on 2026-09-06 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_studentenrollment_schoolclass'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date'), name='unique_enrollment_attendance_per_day'),
        ),
    ]
