# Generated by Django 6.1 on 2026-09-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_studentattendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
