# Generated by Django 6.1 on 2026-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_studentattendance_status'),
        ('teachers', '0003_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_attendance_per_day'),
        ),
    ]
