# Generated by Django 6.1 on 2026-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_covers/'),
        ),
    ]
