# Generated by Django 6.1 on 2026-08-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='schoolclass',
        ),
    ]
