# Generated by Django 6.1 on 2026-08-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_schoolclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='section',
            new_name='class_section',
        ),
    ]
