# Generated by Django 6.1 on 2026-09-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_section_assignment_class_section'),
        ('students', '0006_remove_student_schoolclass_remove_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmisssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='assignment')),
                ('remarks', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
