# Generated by Django 6.1 on 2026-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_schoolclasses'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='schoolclass',
        ),
        migrations.AddField(
            model_name='exam',
            name='schoolclass',
            field=models.ManyToManyField(to='academics.schoolclass'),
        ),
    ]
