# Generated by Django 6.1 on 2026-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='staff/')),
                ('address', models.TextField()),
                ('staff_type', models.CharField(choices=[('Peon', 'Peon'), ('Security', 'Security'), ('Helper', 'Helper'), ('Librarian', 'Librarian'), ('Gardener', 'Gardener'), ('Accountant', 'Accountant'), ('Other', 'Other')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
