# Generated by Django 6.1 on 2026-08-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschedule',
            old_name='room',
            new_name='room_no',
        ),
    ]
