# Generated by Django 6.1 on 2026-08-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffpayments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpayment',
            name='payment_month',
        ),
    ]
