# Generated by Django 6.1 on 2026-08-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
            ],
        ),
    ]
