# Generated by Django 6.1 on 2026-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
