# Generated by Django 6.1 on 2026-08-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teacherassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='schoolclass',
            field=models.ManyToManyField(related_name='subjects', to='academics.schoolclass'),
        ),
    ]
