# Generated by Django 6.1 on 2026-08-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_schoolclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='schoolclass',
            new_name='schoolclasses',
        ),
    ]
