# Generated by Django 6.1 on 2026-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_rename_schoolclass_subject_schoolclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='schoolclasses',
            field=models.ManyToManyField(to='academics.schoolclass'),
        ),
    ]
