# Generated by Django 6.1 on 2026-09-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_schoolclasses'),
        ('students', '0005_rename_schooclass_student_schoolclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subject_name'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='schoolclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('section', 'academic_year', 'roll_no'), name='unique_roll_no_in_section_year'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_in_academic_year'),
        ),
    ]
