# Generated by Django 6.1 on 2026-09-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_studentenrollment_subject_unique_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='schoolclass',
        ),
    ]
