# Generated by Django 6.1 on 2026-09-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_studentenrollment_schoolclass'),
        ('students', '0005_rename_schooclass_student_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
    ]
