# Generated by Django 6.1 on 2026-09-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_studentenrollment_student'),
        ('teachers', '0003_teacher_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'academic_year'), name='unique_class_teacher_per_section_year')],
            },
        ),
    ]
