# Generated by Django 6.1 on 2026-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ManyToManyField(to='academics.subject'),
        ),
    ]
