# Generated by Django 6.1 on 2026-09-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='subject',
            new_name='subjects',
        ),
    ]
