# Generated by Django 6.1 on 2026-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_amount_fee_total_amount_fee_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('Tution', 'Tution Fee'), ('Admission', 'Admission Fee'), ('Registration', 'Registration Fee'), ('Annual', 'Annual Fee'), ('Examination', 'Examination Fee'), ('Transport', 'Transport Fee'), ('Library', 'Library Fee'), ('Computer/Lab', 'Computer/Lab Fee'), ('Activity', 'Activity Fee'), ('Sports', 'Sports Fee'), ('Miscellaneous', 'Miscellaneous Fee'), ('Late', 'Late Fee'), ('Hostel', 'Hostel Fee')], max_length=100, null=True),
        ),
    ]
