# Generated by Django 6.1 on 2026-08-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_fee_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('Tuition', 'Tuition Fee'), ('Admission', 'Admission Fee'), ('Registration', 'Registration Fee'), ('Annual', 'Annual Fee'), ('Examination', 'Examination Fee'), ('Transport', 'Transport Fee'), ('Library', 'Library Fee'), ('Computer/Lab', 'Computer/Lab Fee'), ('Activity', 'Activity Fee'), ('Sports', 'Sports Fee'), ('Miscellaneous', 'Miscellaneous Fee'), ('Late', 'Late Fee'), ('Hostel', 'Hostel Fee')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.fee')),
            ],
        ),
    ]
