# Generated by Django 6.1 on 2026-08-30 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_fee_fee_type_remove_fee_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeitem',
            name='fee',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.feeitem'),
        ),
    ]
