# Generated by Django 6.1 on 2026-08-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_remove_feeitem_fee_fee_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='fee_type',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_items',
            field=models.ManyToManyField(blank=True, to='fees.feeitem'),
        ),
    ]
