# Generated by Django 6.1 on 2026-08-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_schoolclasses'),
        ('fees', '0006_remove_fee_fee_type_fee_fee_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='schoolclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
    ]
