# Generated by Django 6.1 on 2026-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_fee_section_feeitem_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], default='Cash', max_length=50, null=True),
        ),
    ]
